### ISSUE TITLE
error: couldn't find a replication controller with source id == default/cncfdemo

### ISSUE THREAD

**Issue by UncleRedBeard** [olsc-devops/bbc#2]
Log output from failed build. I tried modifying both the Jenkinsfile and kubernetes/cncfdemo.yml, but couldn't quite get it to work. Will continue debugging, but need additional eyes on it.

Stage Logs (Deploy new image to kubernetes)
 Shell Script -- kubectl rolling-update cncfdemo --image devnode:5000/mynode --image-pull-policy Always (self time 1s)
+ kubectl rolling-update cncfdemo --image devnode:5000/mynode --image-pull-policy Always
Command "rolling-update" is deprecated, use "rollout" instead
error: couldn't find a replication controller with source id == default/cncfdemo

**Comment by UncleRedBeard** [comment]
Please use the 'rc-error' branch for debugging / resolving this error. Once resolved, we'll merge this into the 'dev' branch for final testing/validation before the final merge into the 'master' branch

**Comment by shawnkelley-olvsc** [comment]
**References**

* [Rolling Updates with Kubernetes Deployments](https://tachingchen.com/blog/kubernetes-rolling-update-with-deployment/)

**Comment by shawnkelley-olvsc** [comment]
pulled latest update and deployed app...everything looks good.

closing issue and merging
